include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - sort_pub_dependencies

analyzer:
  plugins:
    - custom_lint
  errors:
    body_might_complete_normally_nullable: ignore
    invalid_annotation_target: ignore
    use_build_context_synchronously: ignore
    curly_braces_in_flow_control_structures: ignore
    non_constant_identifier_names: ignore
  exclude:
    - "**/*.g.dart"
    - "**/*.gr.dart"
    - "**/*.freezed.dart"
    - "mock_server/**"
